### ISSUE TITLE
Final Polish Checklist

### ISSUE THREAD

**Issue by irrelevantirreverent** [ConanODoyle/farming#37]
Required:
- [x] Clear server config stuff for launch
- [x] Weedkiller needs a buy price
- [x] Put quest events in place (in build)
- [x] Add tool buyer
- [x] Test Big Buyer
- [x] Update desert crop seller
- [x] Finish tutorial dialogue (https://github.com/ConanODoyle/farming/issues/22)
- [x] Gems need a shop value and a bot to buy them from you
- [x] Town needs a Supermarket Buyer
- [x] License bot so people can buy crop licenses to buy crops
- [x] Edit setBotName to set shape names

Nice-to-haves:
- [ ] Tier 2 processors (https://github.com/ConanODoyle/farming/issues/35)
