### ISSUE TITLE
Checklist for reopen

### ISSUE THREAD

**Issue by ConanODoyle** [ConanODoyle/farming#39]
Priority is in order top/down for each subsection

- ### Fishing
- [x] fish exp rewards, prices
- [x] fishing rod, tackle box, fish finder costs
- [x] make fish placable in storage containers
- [ ] fishing sounds
- [ ] email "phish" (Irrel)
- [ ] fish cooler
- [ ] rodney
- ### Production
- [ ] Cannery
- ### Tools/Info
- [x] croptrak, old boot, empty can model
- [ ] water removal tool (Conan)
- [x] repair kit (Was Already Done By Irrel)
- [x] talk about croptrak bonuses more (Conan)
- [x] add /upgradeinventory info bot in town
- [x] update cropmaster text
- [x] wowew chance of m-maxweww showing up in s-shop
- [x] update tutorial
- ### Bugs
- periodically revalidate energy systems [cancelled debug - check to see if issue arises again first]
- [x] fix planting trees across multiple lots
- [x] make trees check random positions LOS upwards
- [x] phosphate and nitrate retrieval debugging
- [x] fix falling through lot
- ### GUI/UX
- [x] check out the Nutrients are maxed out! spam
- [x] make organic anal tell you if it needs shit now or later
- [x] make organic anal include the effect of weed
- [x] new loading screen
- [x] item icons
- [ ] centerprint sorting??? low priority
- ### Design
- [x] add prices to new items, add new items to quest tables
  - repair tool
  - crop trak
  - upgrade tool (durability)
  - fishing poles
  - fish finder
  - tackle box
- [x] harvester reward tools being repairable/croptrakable
- [x] croptrak harvest bonus calculator
- [ ] brainstorm more power stuff like auto harvesters
- [ ] consider research trees, converting electrical system quests to be a "research" unlocker rather than an individual "purchase"
- ### Secret
- [x] selectiveghosting for environment zones/weather support for environment zones
- [x] unique ruins flowerpots that turn the correct flower black
- [x] model void plant, broken void key crop, fixed void key crop (should probably look like a rusty key)
